export const REGISTER_PROFILE_COMPONENT = 'REGISTER_PROFILE_COMPONENT';
export const REGISTER_CONTACTS_COMPONENT = 'REGISTER_CONTACTS_COMPONENT';
export const REGISTER_MESSAGES_COMPONENT = 'REGISTER_MESSAGES_COMPONENT';

/* LOGIN actions*/
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

/* PROFILE actions */
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const SUBMIT_PROFILE = 'SUBMIT_PROFILE';
export const SUBMIT_PROFILE_SUCCESS = 'SUBMIT_PROFILE_SUCCESS';
export const SUBMIT_PROFILE_ERROR = 'SUBMIT_PROFILE_ERROR';

/* CONTACTS actions*/
export const SELECT_CONTACT = 'SELECT_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const SUBMIT_CONTACT = 'SUBMIT_CONTACT';
export const SUBMIT_CONTACT_SUCCESS = 'SUBMIT_CONTACT_SUCCESS';
export const SUBMIT_CONTACT_ERROR = 'SUBMIT_CONTACT_ERROR';

export const DELETE_CONTACT = 'DELETE_CONTACT';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR';

export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_ERROR = 'GET_CONTACTS_ERROR';

/* MESSAGES actions */
export const SELECT_MESSAGE = 'SELECT_MESSAGE';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const SUBMIT_MESSAGE = 'SUBMIT_MESSAGE';
export const SUBMIT_MESSAGE_SUCCESS = 'SUBMIT_MESSAGE_SUCCESS';
export const SUBMIT_MESSAGE_ERROR = 'SUBMIT_MESSAGE_ERROR';

export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_ERROR = 'DELETE_MESSAGE_ERROR';

export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_ERROR = 'GET_MESSAGES_ERROR';