export const REGISTER_PROFILE_COMPONENT = 'REGISTER_PROFILE_COMPONENT';
export const REGISTER_CONTACTS_COMPONENT = 'REGISTER_CONTACTS_COMPONENT';
export const REGISTER_MESSAGES_COMPONENT = 'REGISTER_MESSAGES_COMPONENT';
export const REGISTER_EVENT_COMPONENT = 'REGISTER_EVENT_COMPONENT';

/* LOGIN actions*/
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

/* PROFILE actions */
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const SUBMIT_PROFILE = 'SUBMIT_PROFILE';
export const SUBMIT_PROFILE_SUCCESS = 'SUBMIT_PROFILE_SUCCESS';
export const SUBMIT_PROFILE_ERROR = 'SUBMIT_PROFILE_ERROR';

/* CONTACTS actions*/
export const SELECT_CONTACT = 'SELECT_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const SUBMIT_CONTACT = 'SUBMIT_CONTACT';
export const RESET_CONTACT = 'RESET_CONTACT';
export const SUBMIT_CONTACT_SUCCESS = 'SUBMIT_CONTACT_SUCCESS';
export const SUBMIT_CONTACT_ERROR = 'SUBMIT_CONTACT_ERROR';

export const DELETE_CONTACT = 'DELETE_CONTACT';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR';

export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_ERROR = 'GET_CONTACTS_ERROR';

/* MESSAGES actions */
export const SELECT_MESSAGE = 'SELECT_MESSAGE';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';

export const READ_MESSAGE = 'READ_MESSAGE';
export const READ_MESSAGE_SUCCESS = 'READ_MESSAGE_SUCCESS';
export const READ_MESSAGE_ERROR = 'READ_MESSAGE_ERROR';

export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_ERROR = 'DELETE_MESSAGE_ERROR';

export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_ERROR = 'GET_MESSAGES_ERROR';

/* EVENTS actions*/
export const SELECT_EVENT = 'SELECT_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const SUBMIT_EVENT = 'SUBMIT_EVENT';
export const RESET_EVENT = 'RESET_EVENT';
export const SUBMIT_EVENT_SUCCESS = 'SUBMIT_EVENT_SUCCESS';
export const SUBMIT_EVENT_ERROR = 'SUBMIT_EVENT_ERROR';

export const DELETE_EVENT = 'DELETE_EVENT';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_ERROR = 'DELETE_EVENT_ERROR';

export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR';